name: CI WebdriverIO TV Labs Service

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: npm run format:check

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
